server:
  port: 8088

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url:  jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: zemfira1597!
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update





